TASK RUNNERS NPM. Tested the 'npm run static:img:compressed' with webp compression
This option works on Windows and Ubuntu, but on Mac I have some bugs:

Error: Command failed: /Applications/MAMP/htdocs/task-runners/task-runners-npm/node_modules/cwebp-bin/vendor/cwebp static/src/images/content/fauna/png-2687339.png -o static/dist/images/content/fauna/png-2687339.webp
libpng warning: iCCP: known incorrect sRGB profile
Saving file 'static/dist/images/content/fauna/png-2687339.webp'
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/MAMP/htdocs/task-runners/task-runners-npm/node_modules/cwebp-bin/vendor/cwebp (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/MAMP/htdocs/task-runners/task-runners-npm/node_modules/cwebp-bin/vendor/cwebp (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Online tool for convert png to webp files:
https://imagen.online-convert.com/es/convertir-a-webp

How to enable webp image format preview on the macos finder:
https://ourcodeworld.com/articles/read/1160/how-to-enable-webp-image-format-preview-on-the-macos-finder